---
# See https://pre-commit.com for more information
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      # NOTE: Leave these artifacts as they are, it will only create trouble
      # with GA commits where these tools are not installed.
      - id: end-of-file-fixer
        exclude: |
          (?x)^(
              data/intel-mediasdk-gcc13\.patch|
              npm-generated-sources\.json|
              nuget-generated-sources-arm64\.json|
              nuget-generated-sources-x64\.json
          )$
      # NOTE: Disabled because it fails at:
      # could not determine a constructor for the tag '!=:'
      #- id: check-yaml
      - id: check-added-large-files
      # non-default
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      #- id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: detect-private-key
      - id: mixed-line-ending
      # NOTE: Disabled, there is currently no use for this.
      #- id: pretty-format-json
      #  args: ["--autofix"]
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.10.0
    hooks:
      - id: shellcheck
        args: ["--color=always", "--external-sources"]
        types: ["file", "shell", "text"]
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.10.0-1
    hooks:
      - id: shfmt
        args: ["--diff", "--indent", "2", "--binary-next-line", "--space-redirects", "--case-indent"]
        #types: ["executable", "file", "shell", "text"]
        types: ["file", "shell", "text"]
        exclude: |
          (?x)^(
              path/to/file\.py
          )$
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.21.2
    hooks:
      - id: gitleaks
        args: ["--no-banner"]
