name: NuGet Checker

on:
  #schedule:
  #- cron: 0 0/12 * * *
  workflow_dispatch:
env:
  MANIFEST: "main/org.jellyfin.JellyfinServer.yml"

jobs:
  NuGet-Checker:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        path: main

    - name: Check if branch exists
      working-directory: main
      run: |
        if [[ -n "$(git ls-remote --heads origin update-nuget)" ]]; then
          echo "Warning: Branch 'update-nuget' exists. Merge the PR or delete the branch."
          exit 1
        fi

    - name: Restore Flatpak Cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.local/share/flatpak
        key: flatpak-cache-x86_64-${{ github.sha }}
        restore-keys: |
          flatpak

    - name: Setup Dependencies Flatpak
      run: |
        sudo apt-get update -y
        sudo apt-get install flatpak -y --no-install-recommends

    - name: Setup Dependencies yq
      run: |
        mkdir -pv ~/.local/bin
        wget --quiet https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O ~/.local/bin/yq
        chmod -v +x ~/.local/bin/yq

    - name: Set ENV Variables
      run: |
        # TEST
        #"$GITHUB_ENV" <<< "YQ_RUNTIME_VERSION=$(yq '.runtime-version' ${{ env.MANIFEST }})"
        # Freedesktop SDK runtime rersion, example: 24.08
        echo "YQ_RUNTIME_VERSION=$(yq '.runtime-version' ${{ env.MANIFEST }})" >> "$GITHUB_ENV"
        echo "YQ_DOTNETSDK=$(yq '.sdk-extensions[0]' ${{ env.MANIFEST }})" >> "$GITHUB_ENV"
        # Jellyfin tag
        echo "YQ_TAG=$(yq '.modules[-1].sources[2].tag' ${{ env.MANIFEST }})" >> "$GITHUB_ENV"
        #"$GITHUB_ENV" <<< "DOT_NET_VER=${YQ_DOTNETSDK##*dotnet}"
        echo "DOT_NET_VER=${YQ_DOTNETSDK##*dotnet}" >> "$GITHUB_ENV"

    - name: Checkout Jellyfin
      uses: actions/checkout@v4
      with:
        repository: jellyfin/jellyfin
        path: jellyfin
        ref: ${{ env.YQ_TAG }}

    - name: Checkout Flatpak Builder Tools
      uses: actions/checkout@v4
      with:
        repository: flatpak/flatpak-builder-tools
        path: flatpak-builder-tools

    - name: Install Freedesktop SDK and DotNet Runtime
      run: |
        flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
        flatpak update -y
        flatpak install --user flathub org.flatpak.Builder -y
        flatpak install --user flathub org.freedesktop.Sdk//${{ env.YQ_RUNTIME_VERSION }} -y
        flatpak install --user flathub ${{ env.YQ_DOTNETSDK }}//${{ env.YQ_RUNTIME_VERSION }} -y
        
    - name: Generate cache for NuGet x64
      run: |
        ./flatpak-builder-tools/dotnet/flatpak-dotnet-generator.py \
          --dotnet ${{ env.DOT_NET_VER }} --freedesktop ${{ env.RUNTIME_VER }} --runtime=linux-x64 \
          main/nuget-generated-sources-x64.json \
          jellyfin/Jellyfin.Server/Jellyfin.Server.csproj

    - name: Generate cache for NuGet arm64
      run: |
        ./flatpak-builder-tools/dotnet/flatpak-dotnet-generator.py \
          --dotnet ${{ env.DOT_NET_VER }} --freedesktop ${{ env.RUNTIME_VER }} --runtime=linux-arm64 \
          main/nuget-generated-sources-arm64.json \
          jellyfin/Jellyfin.Server/Jellyfin.Server.csproj

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@5e914681df9dc83aa4e4905692ca88beb2f9e91f # v7.0.5
      with:
        path: main
        title: Update NuGet Cache
        commit-message: Update NuGet Cache
        branch: update-nuget
        delete-branch: true
